name: Unit test
on:
  push:
    branches:
      - 'master'
      - 're_dev'
      - 'cicd'
  pull_request:
    branches:
      - 'master'
      - 're_dev'
      - "cicd"

jobs:
   # Job 1 : unit test
  unit-test:
    name: 'Do unit test to cookly project'
    runs-on: ubuntu-latest
    steps:
    - name: Setup github action (CI)
      uses: actions/checkout@v2
    - name: Setup Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Running unit test
      run: go test ./... -cover

  build-push-docker:
    name: 'Build images and push to the registry'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t geraldiors/cookly_api:1.0.0 .
      - name: Login to registry docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image to registry docker hub
        run: docker push geraldiors/cookly_api:1.0.0
