name: "Unit test"
on:
  push:
    branches:
      - "master"
      - "re_dev"
  pull_request:
    branches:
      - "master"
      - "re_dev"

jobs:
   # Job 1 : unit test
  unit-test:
    name: "Do unit test to cookly project"
    runs-on: ubuntu-latest
    steps:
      - name: Setup github action (CI)
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Running unit test
        uses: go test ./... -cover